### ISSUE TITLE
String casting for dimensions in CommonAttributes + default dimensions

### ISSUE THREAD

**Issue by draui** [norbybaru/laravel-aws-timestream#33]
Hi @norbybaru, thanks for your great library.

I can't use it properly because there 2 issues that mentioned. I've fixed it on my own repository.

It could be great if I could open a PR.

Anyway, there missing of casting to string on PayloadBuilder.php:49
+ no default set for $dimensions. So i'm getting an error that there on initial value. (Actually, it can be an empty array)

Thanks again.

**Comment by norbybaru** [comment]
Hi @draui  feel free to create a PR to fix the issue but I will suggest you update your package to the latest release.

We release `v0.3.0` which doesn't introduce breaking changes but has better intergration
